DNA = "TTTCTCTCGTCTCAAAGACTTCTACCCACGATAATTATGGGAATATGATTGGCGTTGATGGAGCAGCCTGCTACCGAAGCCTTCGCTCTGTGCTTAGATGAGTCTCCAATAGCTCAGCAGCAAAGGAGTATTTGGTGTGTTCCTACGTAGTCAAGTCCTCATAGCTCGGAGGGCCCCTGTCAAACGGGCCGGGCGCCGCTCATCCTCAGGGGGGATGTACGATCCGTGATTTTTTGGGTATCCGGGTATCATGGCCAGAGGTGTTAAGAAACCTATTGCCGAGCTCGAACGGTGTTAAGATTCTTTGTTTTGCCATCTCCAGGATGGGCTGTATAAGGTTGCACCAGGAGCTGCTCTTCCATTAGCAGTATATTCGTAATGAGGCCGTCGGGACCAATCCTGCTCGGGGGAGACTACCACAAAGCGCGGTAGGTTCAAGAATTGTAGCTTGACGGCGATGCCTGCATTTAGATCGAAGTAGATCCCCCTGATCGCGGATCGTGGCAAAAGAATGACCCACGCTTCATTACCAGTCGTCTCCATAGCTTCTTCCGAAATTGCACACATACTATACAAACGTCGGACAGAGGCGGCATTTGCGCTAACCACAACGTGACGTCAAGGCTTGGTATCGGCTACCCCGCCATAGGCGCGGCATCGATCCTCCACGATTAAATATTGTTAAAGATCACCGTGTTTCCTTCCTAAAGCCGTCCCCACTGAATCGAATCAACATTGCATGTTCGGCACGAGTTACCCCGTCTAGCAATATGATCACAGTGGAAGTAAAGATGGTTCATCGCTAGACTATAACTATAGGTCAGCCTACATGCCTCTCCAAACCTGTGGGAAAAGGTTCTTACAGGATACTCATTACCATAGCTACTTCTAAGTTGGCCAGTGTATTAACGGGAGAAGCACGACGAGTATGGAGGCATTGAAAAGCAA"

# open empty list
res = []
# for loop over reversed [::-1] string, appending result to list
for i in DNA[::-1]:
    if i == "A":
        res.append("T")
    elif i == "C":
       res.append("G")
    elif i == "G":
       res.append("C")
    elif i == "T":
        res.append("A") 

#print list without white spaces
print "".join(res)
